version: "3.4"
services:
     web:
          build: .
          command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
          volumes: 
               - .:/code
          ports:
               - "8080:8080"
          restart: on-failure